### ISSUE TITLE
石井作業現場整理

### ISSUE THREAD

**Issue by ishiitakeru** [forthelocal/azureadb2ctest01#6]

**Comment by 164c** [comment]
@ishiitakeru  本番ではB2Cを使いますが、それがB2Cにビルトインされている画面を使おうが使うまいが、こっちが開発するわけじゃないからいいんです。

> するとB2Cの調査はフロント側から呼び出される共通基盤処理として実装するために必要？

そのとおりです。
シーケンスにある、ログイン〜グループ選択含めてインドが実装する前提でよいです。

一方で、フロントアプリチームが開発・動作確認テストを行う上で、インドの実装がないと動作確認できないのは困ってしまいますよね。なので、ローカルでは、インドが実装する範囲であるログイン〜グループ選択の簡易的なモック実装が必要だと考えています。

なお、セッション機能については、石井くんの認識と同じ認識でいます。

**Comment by 164c** [comment]
@ishiitakeru @ogawaso @higan96 
なお、課題がクリアできれば方法は問いません。他にいい方法があれば提案くだされ。
